// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_WRoE0ceWkgp0anv_HWPcQj9xiklm_eU',
    appId: '1:232185485705:web:e2b0deb9c0763fbc482958',
    messagingSenderId: '232185485705',
    projectId: 'chat-app-671b6',
    authDomain: 'chat-app-671b6.firebaseapp.com',
    storageBucket: 'chat-app-671b6.firebasestorage.app',
    measurementId: 'G-R95ERFDZKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxi3uMhh5R5_gMf_oukEJ4jhKIYMUNg4w',
    appId: '1:232185485705:android:b5983d53c85be655482958',
    messagingSenderId: '232185485705',
    projectId: 'chat-app-671b6',
    storageBucket: 'chat-app-671b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFYPCjIW0rr-3iv-uEniv_ManwCSGJXqM',
    appId: '1:232185485705:ios:01bd44a7d7198c11482958',
    messagingSenderId: '232185485705',
    projectId: 'chat-app-671b6',
    storageBucket: 'chat-app-671b6.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFYPCjIW0rr-3iv-uEniv_ManwCSGJXqM',
    appId: '1:232185485705:ios:01bd44a7d7198c11482958',
    messagingSenderId: '232185485705',
    projectId: 'chat-app-671b6',
    storageBucket: 'chat-app-671b6.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_WRoE0ceWkgp0anv_HWPcQj9xiklm_eU',
    appId: '1:232185485705:web:47998cd1544c7847482958',
    messagingSenderId: '232185485705',
    projectId: 'chat-app-671b6',
    authDomain: 'chat-app-671b6.firebaseapp.com',
    storageBucket: 'chat-app-671b6.firebasestorage.app',
    measurementId: 'G-M2XJEBFYL4',
  );
}
